name: maa-ai
channels:
- conda-forge
- defaults

dependencies:
- python=3.11
- pip
- faiss-cpu
- sentence-transformers
- pypdf
- uvicorn
- fastapi
- pip:
  - llama-cpp-python
  - langchain
  - langchain-community
